services:
  backend:
    build: ./backend
    ports:
      - "8500:8500"
    environment:
      LINKEDIN_LI_AT: ${LINKEDIN_LI_AT}
      LINKEDIN_JSESSIONID: ${LINKEDIN_JSESSIONID}
    restart: always
